# Generated by Django 4.2.6 on 2023-10-07 11:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KAI',
            fields=[
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.admin')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyAndStaff',
            fields=[
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('no_students', models.IntegerField()),
                ('no_faculty', models.IntegerField()),
                ('no_staff', models.IntegerField()),
                ('departments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.admin')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=255)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.admin')),
                ('collage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.collage')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.facultyandstaff')),
            ],
        ),
    ]
